USStateDept/State-TalentMAP-API

- DOCKER.md
- Dockerfile
- docker-compose.yml
This PR contains the setup for a minimally functional docker-compose dev setup.
Upon first use after `docker-compose build`, you might get an error that the app is not able to connect to the database (something like `File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection self.connect()`).  This is because the postgres service hasn't completely finished starting up when the Django app tries to connect to it. You could add some additional wait logic as in https://github.com/18F/calc/blob/develop/docker_django_management.py#L162 to mitigate this issue.
> Minimal working docker-compose dev setup

- SETUP.md
- docker-compose.yml
The docs for `DJANGO_DEBUG` had the inverse of that setting's default value. This PR is a correction to the documentation and also adds `DJANGO_DEBUG=true` to docker-compose.yml so that the dockerized app will run in debug mode.
also:
- use port 8000 in docker-compose to mirror native setup
- add `db` to `depends_on section` of web app in docker-compose
> Clarify DJANGO_DEBUG setting; add to docker-compose env

- Dockerfile
No reason to set `PORT` in the Dockerfile.
> Remove spurious PORT env var

- talentmap_api/common/filters.py
- talentmap_api/language/filters.py
- talentmap_api/organization/filters.py
- talentmap_api/position/filters.py
- talentmap_api/settings.py
This PR fixes a bug @mjoyce91 found, where a filter applied to a reverse many-to-many relationship would not function correctly.
```
>>> TourOfDuty.objects.filter(posts__positions__isnull=False).distinct().values_list("id", flat=True)
<QuerySet [1, 6, 7, 8, 11, 12, 17, 19, 20]>
>>> TourOfDuty.objects.exclude(posts__positions__isnull=True).distinct().values_list("id", flat=True)
<QuerySet [19]> 
```
This output exemplifies the problem. The filters were performing the second logic, when it was expect that they would perform the first. This PR resolves that issue, as well as adds in the ordering backend to support response ordering.
Additionally, it was not possible to use `__in` on a foreign key relationship, because they were not explicitly permitted. This PR resolves this issue as well. …
> M2M Filter Fix, Ordering

- talentmap_api/common/management/commands/load_xml.py
- talentmap_api/common/tests/test_sharing.py
- talentmap_api/common/views.py
- talentmap_api/urls.py
This response issue #40 
* Created `/api/v1/share/` which accepts a post body to support internal and external sharing of various TalentMAP objects
* Currently supports sharing `position`
* Currently supports sharing via `email` - This is "spoofed", in that the response from the server will be `202 ACCEPTED` but does not actually send an e-mail as we are not sure of what sort of email services we will have access to yet
* Added tests for `/api/v1/share/` endpoint and its validator
* Fixed a small bug where TOD descriptions were loaded into the wrong fields
Tagging @jseppi as an additional reviewer in case @burgwyn is too busy with his move.
> Share endpoint

- talentmap_api/common/filters.py
- talentmap_api/common/tests/test_ordering.py
- talentmap_api/settings.py
This PR adds tests and fixes for a bug with the DRF ordering functionality, wherein ordering on a nested field would not produce any effect.
i.e. `/api/v1/postion/?ordering=skill__description` would not order on the skill description as you would expect. Now it does.
Tagging @mjoyce91 for visibility
> Ordering Fixes

- talentmap_api/common/pagination.py
- talentmap_api/common/tests/test_endpoints.py
- talentmap_api/common/tests/test_ordering.py
- talentmap_api/language/models.py
- talentmap_api/language/tests/test_language_endpoints.py
- talentmap_api/organization/models.py
- talentmap_api/organization/tests/test_organization_endpoints.py
- talentmap_api/position/models.py
- talentmap_api/position/tests/test_position_endpoints.py
- talentmap_api/position/tests/test_position_full_text_search.py
- talentmap_api/settings.py
- talentmap_api/user_profile/models.py
This PR addresses #77 
* Adds basic page/limit pagination to all endpoints that return multiple objects
* Adds query parameters:
- `page` - the page number to view; accepts "end", "final", and "last" to jump to the last page
- `limit` - the max number of items per page; default `100` and max `1000`
* Adds default ordering to all models, to ensure pagination is consistent across queries
* Updates relevant tests to use pagination
New response object looks like this:
```
{
"count": 1234  // Total number of items
"next": http://url.to.next.page/?page=3
"previous": http://url.to.next.page/?page=1
"results": [ all the data in this array ]
}
```
> Pagination

- talentmap_api/common/tests/test_sharing.py
- talentmap_api/user_profile/views.py
This PR handles issue #74 
* Switch sharing to infer internal/external by e-mail
* When sharing, if destination user has `state.gov` email address, share internally. Otherwise, share externally
@mjoyce91 this removes the need for `mode` in the request object
> Switch to sharing inference

- talentmap_api/common/management/commands/load_xml.py
- talentmap_api/common/xml_helpers.py
This takes care of #70 
- Uses list provided by DoS to canonize country names to identical formatting
- pseudo placeholder until we get a full location integration to HREX
> Canonize country

- requirements.txt
- talentmap_api/common/renderers.py
- talentmap_api/settings.py
This PR handles #79 
Quick list:
* Adds `?format` option to all endpoints, supporting `json` `csv` and `api` (HTML browsable API)
* Adds `?include` and `?exclude` options to all endpoints, supporting dynamic field selection
Details:
This PR adds the venerable `?format=csv` option to all endpoints. It will render whatever data would have been returned with `?format=json`, but as a flattened CSV instead. It respects all filters, ordering, and pagination options in the query parameters. (i.e. `?limit=10` will return only 10 items, etc.) Examples:
`/api/v1/positions/?q=german&format=csv` - download all positions on the first page of the search matching FTS for 'german'
`/api/v1/positions/?limit=1000&grade__code=05` - download the first 1000 positions whose grade code is 05
Additionally, this …
> CSV Downloads, Field Limiting

- talentmap_api/position/tests/test_position_endpoints.py
- talentmap_api/position/urls/position.py
- talentmap_api/position/views.py
This PR handles #112 
Follows how github handles starring gists: https://developer.github.com/v3/gists/#star-a-gist
Adds:
- GET `/api/v1/position/{pk}/favorite/` - Returns 204 if the position is the logged in user's favorite, or 404 otherwise
- PUT `/api/v1/position/{pk}/favorite/` - Returns 204, adds the position as the logged in user's favorite 
- DELETE `/api/v1/position/{pk}/favorite/` - Returns 204, removes the position from the logged in user's favorites
@mjoyce91 you can still do a mass-update by PATCHing the user profile favorites list with an array of ids
> Favorite action endpoint

- talentmap_api/common/serializers.py
- talentmap_api/language/serializers.py
- talentmap_api/messaging/serializers.py
- talentmap_api/position/serializers.py
- talentmap_api/user_profile/serializers.py
This PR addresses #107 
Adding @jseppi as a reviewer since this was his issue
- Added functionality to `PrefetchedSerializer` (which all serializers we use inherit from) to set all fields to be `read_only` _unless_ they are present in a `writable_fields` option in the descendant serializer's `Meta` class. This replicates the functionality of DRF native `read_only_fields` in the inverse, and doesn't step on the functionality of other DRF `Meta` based code
- Updated all relevant serializers to specify `writable_fields`
> Default read only serializers

- talentmap_api/common/serializers.py
- talentmap_api/common/tests/test_sharing.py
- talentmap_api/messaging/views.py
- talentmap_api/position/views.py
@jseppi This addresses your comments on the Sprint 7 PR
Additionally
- Adds a few extra tests for sharing
- Updates the common serializer to perform Validation to ensure that no invalid data is being written, and to properly send back a 400 error in the case that a partial update object is empty after stripping out invalid data.
> Fixing PR requests, also adding extra validation and tests

- talentmap_api/bidding/models.py
- talentmap_api/bidding/tests/test_bidlist.py
Addresses #162 
Fires notifications:
- When a bid is declined, the bidder receives a notification
- When a bid has a handshake offered, the bidder receives a notification; and all other bidders for that position receive a notification
- Adds tests for the new notifications
> Add handshake notifications, tests

- talentmap_api/bidding/tests/test_bidcycle.py
- talentmap_api/bidding/urls/bidcycle.py
- talentmap_api/bidding/views/bidcycle.py
- talentmap_api/user_profile/models.py
- Adds PUT `/api/v1/bidcycle/{id}/position/batch/{saved_search_id}` which adds all positions from the saved search to the bid cycle
- This is actually like super cool cause it covers all of the examples Robin showed me last sprint planning + is extensible because you can use any filter to create your batches.
> Add bid cycle batch endpoint

- talentmap_api/bidding/serializers.py
Realized we weren't outwardly displaying the calculated fairshare anywhere. For now I've added it to the status survey, so a CDO can see the self-identified fairshare status and the system calculated fairshare status. 
We'll probably merge this into staging during the next sprint.
> Add calculated fairshare to bidcycle survey

- talentmap_api/user_profile/management/commands/create_seeded_users.py
- talentmap_api/user_profile/serializers.py
- talentmap_api/user_profile/views/client.py
- Nest CDO contact info in a user's profile ( @mjoyce91  for visiblity! )
```
"cdo": {
"username": "shadtrachl",
"first_name": "Leah",
"last_name": "Shadtrach",
"email": "shadtrachl@email.email",
"phone_number": "555-555-5555",
"is_cdo": true
},
```
- Update demo environment creation script to add nationalities, birthdays, and phone numbers
- Update `/api/v1/client/` to use a client serializer that removes some unneeded info (removes cdo, favorites, and shared)
> Add CDO contact info

- talentmap_api/bidding/filters.py
- talentmap_api/language/filters.py
- talentmap_api/messaging/filters.py
- talentmap_api/organization/filters.py
- talentmap_api/permission/filters.py
- talentmap_api/position/filters.py
- talentmap_api/user_profile/filters.py
I removed this a while back because I thought it was causing a bug, but it turns out I was being a bit overzealous. Re-adding FK lookups to the filters.
Right now you can only do something like `/location/?post={id}` but this expands it to allow things like `/location/?post__in={id},{id},{id}` which the front-end needs.
Hopefully we can get this in before #252 :) @jseppi 
@mjoyce91 :eyes:
> Allow extra filters on FK assignments

- talentmap_api/user_profile/models.py
When a user sets DOB via a string, we need to identify this case and convert it to a date to work with relative delta.
> Fix str casting error

- talentmap_api/organization/models.py
- talentmap_api/organization/tests/test_organization_endpoints.py
- talentmap_api/user_profile/tests/mommy_recipes.py
Per ticket, swapped the organization abbreviation and the organization name
`Western Hemispheric Affairs (WHA)` -> `(WHA) Western Hemispheric Affairs`
Will require a flush/reload @mjoyce91 of your local db (also gives you a chance to try the new create_demo_environment :) )
> Swap description ordering for organizations

- .gitignore
- EXAMPLE_setup_environment.sh
- SETUP.md
- talentmap_api/common/common_helpers.py
- talentmap_api/common/tests/test_common_helpers.py
- talentmap_api/data/test_data/test_setup_environment.sh
- talentmap_api/wsgi.py
- Sets up wsgi.py as it should be in deployment
- Creates `EXAMPLE_setup_environment.sh` script as a basis for deployment variable setups (and for prior to manual testing)
- Add `setup_environment.sh` to gitignore
- Add tests for helper function which loads environment variables from file
> Deployment WSGI, environment files

- talentmap_api/common/common_helpers.py
- talentmap_api/common/management/commands/soap_api_test.py
- talentmap_api/settings.py
Suitable for Thursday redeploy; no new libraries required.
`python manage.py soap_api_test` will return a WSDL inspection (listing callable services) - it should show something like this:
`IPMSDataWebService(RequestorID: xsd:string, Action: xsd:string, RequestName: xsd:string, Version: xsd:string, InputParameters: xsd:string, MaximumOutputRows: xsd:string, PaginationStartKey: xsd:string, DataFormat: xsd:string) -> IPMSDataWebServiceResult: {_value_1: ANY}`
`python manage.py soap_api_test IPMSDataWebService RequestorID=TalentMAP Action=GET RequestName=skill Version=0.01 DataFormat=XML` will call "IPMSDataWebService" should return some skills. We may need to pass `InputParameters=<![CDATA[<skills><skill></skill></skills>]]>` but I want to hold off on that.
Should be enough to poke around …
> Update SOAP test to play nice with self signed certs

- talentmap_api/settings.py
Accidentally using incorrect environment variable when setting sls and
consumer services for ADFS
This was resulting in incorrect urls being generated for our XML.
> ADFS bugfix

- EXAMPLE_setup_environment.sh
- talentmap_api/integrations/synchronization_helpers.py
- talentmap_api/settings.py
- talentmap_api/wsgi.py
Separates environment variables when running in WSGI mode
If you're using multiple instances of the software on a single machine, set `DJANGO_ENVIRONMENT_NAME` to keep the environment variables separated.
> (RC1) Add environment delineation

- EXAMPLE_setup_environment.sh
- talentmap_api/integrations/synchronization_helpers.py
- talentmap_api/settings.py
- talentmap_api/wsgi.py
Separates environment variables when running in WSGI mode
If you're using multiple instances of the software on a single machine, set `DJANGO_ENVIRONMENT_NAME` to keep the environment variables separated.
> Add environment delineation

- talentmap_api/bidding/tests/test_bidcycle.py
- talentmap_api/bidding/views/bidcycle.py
- talentmap_api/common/management/commands/create_base_permissions.py
- talentmap_api/common/permissions.py
- Add permission class closure `IsDjangoGroupMemberOrReadOnly` to dynamically create an extension to the current `IsDjangoGroupMember` closure
- Add permission checks to bidcycle endpoints
- Extend tests to cover new functionality
> (RC1) Update bidcycle permissions

- talentmap_api/bidding/tests/test_bidcycle.py
- talentmap_api/bidding/views/bidcycle.py
- talentmap_api/common/management/commands/create_base_permissions.py
- talentmap_api/common/permissions.py
- Add permission class closure `IsDjangoGroupMemberOrReadOnly` to dynamically create an extension to the current `IsDjangoGroupMember` closure
- Add permission checks to bidcycle endpoints
- Extend tests to cover new functionality
> Update bidcycle permissions

- talentmap_api/common/filters.py
- talentmap_api/organization/filters.py
- talentmap_api/position/filters.py
Fixes an issue @mjoyce91 was having
When using `__in` on an M2M foreign key it was treating it like a string. This adds `?has_groups` to support m2m filtering with many id's. `?has_groups=1,2,3` etc.
Can be combined `?has_groups=3,1&groups__name__icontains=congo` with other groups filters.
**NOTE** On the positions endpoint, this filter is `?org_has_groups`
> Organization groups m2m in

- talentmap_api/integrations/synchronization_helpers.py
Fixes a bug where soap synchronization for `availablepositions` was not requesting pages after the first
Resolves #456
> (RC1) Fix bug for pagination on available positions

- talentmap_api/integrations/synchronization_helpers.py
Fixes a bug where soap synchronization for `availablepositions` was not requesting pages after the first
Resolves #456
> Fix bug for pagination on available positions

- talentmap_api/common/common_helpers.py
- talentmap_api/common/tests/test_common_helpers.py
- talentmap_api/integrations/synchronization_helpers.py
Change ensure_date to add the utc_offset, which will properly allow for the incoming date to convert to UTC rather than offsetting after the fact, which was leading to mis-matched dates
Update date SOAP syncs to use utc_offset
> Change ensure_date

- requirements.txt
We received a vulnerability disclosure from GitHub indicating we need to upgrade. From what I see we don't seem to require this library anymore (requirements changed).
> Remove PyYAML

- talentmap_api/fsbid/services/bid_season.py
- talentmap_api/fsbid/services/common.py
- talentmap_api/fsbid/services/projected_vacancies.py
* feature: adds position designations to cycle position stats. TM-695
* fix: filter designations by cycle and position
* fix: 404 if bidcycle or position cannot be found
* feature: handle errors that fsbid may raise when submitting a bid
* adds endpoint to view list of logs available and get the contents of a particular log
* remove unnecessary imports
* log entry model managed should be false
* fixing linting issues
* additional lint errors fixed
* adding endpoints for running data sync ad hoc
* forcing superuser permission and removing unused imports and functions
* fix: remove posted date from PV. TM-909 (#94)
* feature: add endpoints for getting and updating the about page content. TM-912 (#93)
* feature: add endpoints for getting and updating the about page content. TM-912
* chore: …
> staging <- dev (#155)

- deploy.sh
- talentmap_api/common/common_helpers.py
- talentmap_api/fsbid/filters.py
- talentmap_api/fsbid/services/available_positions.py
- talentmap_api/fsbid/urls/available_positions.py
- talentmap_api/fsbid/views/available_positions.py
- talentmap_api/integrations/synchronization_helpers.py
- talentmap_api/settings.py
- talentmap_api/urls.py
- talentmap_api/user_profile/models.py
- talentmap_api/user_profile/serializers.py
- talentmap_api/user_profile/tests/test_saved_searches.py
- talentmap_api/user_profile/views/searches.py
* feature: adds position designations to cycle position stats. TM-695
* fix: filter designations by cycle and position
* fix: 404 if bidcycle or position cannot be found
* feature: handle errors that fsbid may raise when submitting a bid
* adds endpoint to view list of logs available and get the contents of a particular log
* remove unnecessary imports
* log entry model managed should be false
* fixing linting issues
* additional lint errors fixed
* adding endpoints for running data sync ad hoc
* forcing superuser permission and removing unused imports and functions
* fix: remove posted date from PV. TM-909 (#94)
* feature: add endpoints for getting and updating the about page content. TM-912 (#93)
* feature: add endpoints for getting and updating the about page content. TM-912
* chore: …
> dev -> staging (#166)

- .circleci/config.yml
* update filters
* fix count to save on creation
* chore: refactor common functions into common file
* chore: refactor commonn get and count functions
* fix: make requests a little more robust
* adding bidding statistics
* fix: update test
* feature: new model for available position designations which includes highlighting. TM-695
* chore: allow for jwt to be set for swagger calls via authorize (#167)
* fix: update the regex to parse out the language code and reconstruct the representation with better formatting
* fix: add the designations to the returned available_positions data
* fix: use filter+first in case the designation object is not in the db
* add new filter class for available positions that uses the api
* feature: add get individual available position and get similar available …
> dev -> staging (#210)

- .circleci/config.yml
- talentmap_api/fsbid/services/common.py
* chore: refactor common functions into common file
* chore: refactor commonn get and count functions
* fix: make requests a little more robust
* adding bidding statistics
* fix: update test
* feature: new model for available position designations which includes highlighting. TM-695
* chore: allow for jwt to be set for swagger calls via authorize (#167)
* fix: update the regex to parse out the language code and reconstruct the representation with better formatting
* fix: add the designations to the returned available_positions data
* fix: use filter+first in case the designation object is not in the db
* add new filter class for available positions that uses the api
* feature: add get individual available position and get similar available positions
* fix: remove history fields and tables …
> dev -> staging (#213)

- requirements.txt
- talentmap_api/fsbid/services/available_positions.py
- talentmap_api/fsbid/services/reference.py
- talentmap_api/fsbid/tests/test_fsbid_reference.py
- talentmap_api/fsbid/views/reference.py
* Trigger notification
* fix: add location mapping to the projected vacancy. TM-1274
* fix: add verify=False to requests to fsbid
* Revert "fix: add verify=False to requests to fsbid"
This reverts commit aaa689bbdde948e817e21aeb49cc91028a69073c.
* fix: add the verify=false to the fsbid requests
* chore: nosec on verify=False lines
* add api endpoint for updating savedsearch counts
* fix: remove the assignment model and all things associated
* update endpoint
* fix: add to user profile route
* fix: handle multiple favorites
* fix: return all position designations
* safe navigation to the location of the projected vacancy
* fixing bad merge and updating export format
* fix: only return the favorite ids for the profile to shrink the payload
* feature: sort bid season on description
* chore: …
> dev -> staging (#240)

- .gitignore
- EXAMPLE_setup_environment.sh
- deploy.sh
- docker-compose.yml
- requirements.txt
- talentmap_api/fsbid/filters.py
- talentmap_api/fsbid/services/available_positions.py
- talentmap_api/fsbid/services/bid.py
- talentmap_api/fsbid/services/cdo.py
- talentmap_api/fsbid/services/client.py
- talentmap_api/fsbid/services/common.py
- talentmap_api/fsbid/services/employee.py
- talentmap_api/fsbid/services/projected_vacancies.py
- talentmap_api/fsbid/tests/test_fsbid_bidlist.py
- talentmap_api/fsbid/urls/cdo.py
- talentmap_api/fsbid/urls/client.py
- talentmap_api/fsbid/urls/projected_vacancies.py
- talentmap_api/fsbid/views/cdo.py
- talentmap_api/fsbid/views/client.py
- talentmap_api/fsbid/views/projected_vacancies.py
- talentmap_api/settings.py
- talentmap_api/urls.py
- talentmap_api/user_profile/models.py
* fix: allow for location code to be passed to post available position filter. this happens when searching for similar positions
* fix: sort bureau on the short description
* refactor to add error checking
* test file changes
* correctly updating test files this time
* fix: allow sorting on posted_date
* update to have none as default
* codes
* chore: use a docker image rather than require the mock code to be checked out (#150)
* chore: use a docker image rather than require the mock code to be checked out
* fix: move back to mock_fsbid url so containers can still talk to each other;
* feature: allow mock-fsbid to be run from local code if needed
* chore: improve the performance of the string_rep job by forcing update and limiting the fields being updated (#169)
* available positions file …
> dev -> staging (#270)
