README.md

Adding badges for test coverage and code climate

Adding CodeClimate badges

---

requirements.txt
talentmap_api/settings.py

Adding CORS

---

DOCKER.md

Changing the default port from 8080 to 8000

Updating documentation

---

talentmap_api/position/filters.py
talentmap_api/position/tests/test_position_endpoints.py

Another @mjoyce91 bug-finding speciality.
Package string for filters were not defined properly, which made nested filters not work properly.
- Fixed package string
- Added specific filter tests for these filters
@jseppi this is going into dev, but once it's in shall we PR it up to stg as well? (Sorry for missing this case)

Fixing filter package string

---

talentmap_api/common/filters.py
talentmap_api/common/serializers.py
talentmap_api/language/migrations/0005_auto_20170629_2128.py
talentmap_api/language/models.py
talentmap_api/organization/filters.py

Addressing comments from #34 
@jseppi I'll assume if you approve/merge this one that #34 is good to roll in as well.

Addressing comments from PR review

---

talentmap_api/position/views.py
talentmap_api/user_profile/models.py

@jseppi This should fix the issues with the other merge

Fixing documentation issues

---

talentmap_api/common/common_helpers.py
talentmap_api/common/xml_helpers.py
talentmap_api/organization/views.py

- Fixes XML helper boolean parser default arguments
- Adds extra documentation to clarify the functionality of the filter list validator
- Fixes location view descriptions

Fix XML helper args, extra docs

---

talentmap_api/language/filters.py
talentmap_api/organization/filters.py
talentmap_api/position/filters.py
talentmap_api/position/tests/test_position_endpoints.py

This issue handles #67
* Renames declared filter `domestic` to `is_domestic`
* Renames declared filter `available` to `is_available`
@mjoyce91 tagging for visibility

Switch boolean fields to is_X

---

talentmap_api/common/management/commands/load_xml.py
talentmap_api/common/management/commands/update_relationships.py
talentmap_api/common/tests/test_xml_helpers.py
talentmap_api/position/models.py

This PR handles #73 
- Shuffles the order data loads are done
- Adds extra relationship updater to post model

Re-orders and updates entity relationship updaters

---

talentmap_api/user_profile/views.py

Small change to address issue in Sprint 5 PR

Update email check

---

talentmap_api/common/tests/test_endpoints.py
talentmap_api/position/serializers.py
talentmap_api/position/tests/test_capsule_description.py
talentmap_api/position/urls/capsule_description.py
talentmap_api/position/views.py
talentmap_api/urls.py

This PR completes #85 
- Add `/api/v1/capsule_description/` endpoint
- Add Create, Patch, Delete, List, Get to capsule description endpoints
- Add tests for new endpoint/methods

Capsule Description CRUD endpoints

---

talentmap_api/common/mixins.py
talentmap_api/common/serializers.py
talentmap_api/common/tests/test_field_params.py
talentmap_api/language/views.py
talentmap_api/organization/views.py
talentmap_api/position/views.py
talentmap_api/user_profile/views.py

Prior PR #96 didn't have the field limiting code as I forgot to push my commit up. This fixes that.

Field Limiting

---

.dockerignore
Dockerfile

We'll merge this into `dev` then add it to our stg -> master PR

Creating .dockerignore

---

.dockerignore
Dockerfile

Updating `Dockerfile` and adding `.dockerignore`

Staging - Docker ignore

---

MANAGEMENT_COMMANDS.md
talentmap_api/common/common_helpers.py
talentmap_api/organization/models.py
talentmap_api/position/filters.py
talentmap_api/position/tests/test_position_endpoints.py
talentmap_api/position/views.py
talentmap_api/user_profile/management/commands/create_seeded_users.py

- Adds `?is_highlighted` to position filters
- Adds programmatically created permissions for every bureau: `can_highlight_positions_{ORG CODE}`
- Adds functionality to the seeded user generator which will grant some permissions for random bureaus (for demo purposes)
- Updates highlight position tests to validate permissions work

Basic permissions

---

talentmap_api/common/tests/test_common_helpers.py
talentmap_api/organization/models.py

Resolves issues from Sprint 9 PR

Sprint 9 PR fixes

---

talentmap_api/organization/filters.py

Add extra FTS to posts and country endpoints

---

talentmap_api/bidding/models.py
talentmap_api/bidding/tests/test_bidlist.py

- Add notifications for all other bid statuses, add "approved" and "in panel" statuses
- Add tests for new notification triggers
- Refactor notification messages for bid status triggers to generator method

Extra bid status notifications

---

talentmap_api/common/filters.py

Django's FTS doesn't play nice with partial word searches, so I've added `icontains` to the FTS to support some frontend functionality. We should consider hopping over to django-haystack at some point which should resolve the issue and clean up the code a bit; but that's outside of the scope of this sprint.
Tagging @mjoyce91 for visibility

Update FTS method to include icontains

---

talentmap_api/position/models.py
talentmap_api/position/tests/test_assignments.py

It appears`pytest` occasionally doesn't clear the database [_edit_: Don't believe my lies; it was a sneaky ModelMommy recipe sneaking in a Tour of Duty], so we end up with a leftover tour of duty with an incorrect amount of months which is _real weird_. Halloween bugs! 🕷

Test fixes pt 2

---

talentmap_api/common/common_helpers.py
talentmap_api/user_profile/models.py
talentmap_api/user_profile/tests/test_calculated_fields.py

- Add fairshare property to user
- Fairshare is calculated on-the-fly based on the users assignments using standard fairshare rules

Fairshare calculation

---

talentmap_api/bidding/models.py
talentmap_api/bidding/views/bidlist.py
talentmap_api/position/models.py

- Refactor position bid logic into position model (and clean it up a bit)
- Resolve circular dependency
- Change error message

Sprint 11 Fixes

---

.codeclimate.yml
talentmap_api/bidding/serializers.py
talentmap_api/bidding/views/bidcycle.py
talentmap_api/common/common_helpers.py
talentmap_api/language/views.py
talentmap_api/organization/views.py
talentmap_api/permission/views/group.py
talentmap_api/position/views/grade.py
talentmap_api/position/views/skill.py
talentmap_api/user_profile/views/client.py
talentmap_api/user_profile/views/profile.py
talentmap_api/user_profile/views/searches.py

- Update codeclimate.yml to ignore tests and migrations
- Update tolerances on cognitive complexity (mainly due to Validators needing a little extra leeway)
- Update duplication detection to ignore url files (these are necessarily similar)
- Updated some functions to reduce the number of arguments
- Refactored some code to reduce duplication
Annoyingly, there doesn't appear to be a way to disable similarity detection if two files share similarity (e.g. `views/Grade.py` and `views/Skill.py` are very similar) so they'll have to sit there throwing warnings till we add some extra functionality to those views :)

Codeclimate updates

---

talentmap_api/user_profile/models.py
talentmap_api/user_profile/tests/test_calculated_fields.py

Fairshare bidders are people who have _already_ done their fairshare, not the other way around :)

Fix fairshare inverted case

---

.codeclimate.yml

Resolves the warning from codeclimate

Fix codeclimate warning

---

talentmap_api/user_profile/filters.py
talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/tests/test_client_endpoints.py
talentmap_api/user_profile/urls/client.py
talentmap_api/user_profile/views/client.py

- Add FTS to client endpoint
- Add client bid statistics to profiles
- Add client filters for various bid statuses
@mjoyce91 for visibility! @jseppi for review since Nat is out

New client filters

---

EXAMPLE_setup_environment.sh
talentmap_api/bidding/serializers/prepanel.py
talentmap_api/bidding/serializers/serializers.py
talentmap_api/bidding/views/bid.py
talentmap_api/user_profile/models.py
talentmap_api/user_profile/tests/test_client_endpoints.py

Spelling fixes, et al.
Once this is in we can merge the main PR

Kanban set 2 fixes

---

talentmap_api/common/serializers.py
talentmap_api/position/serializers.py
talentmap_api/user_profile/views/client.py

- Add extra stats to client statistics
- Add extra info to client assignments
per @mjoyce91

Add extra bid statistics, client assignment info

---

talentmap_api/user_profile/filters.py
talentmap_api/user_profile/tests/test_client_endpoints.py

Adds requested filter
@mjoyce91

Frontend updates

---

talentmap_api/common/common_helpers.py
talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/views/client.py

Add Assignment to client details view

---

talentmap_api/bidding/urls/bidcycle.py
talentmap_api/bidding/views/bidlist.py
talentmap_api/common/common_helpers.py
talentmap_api/position/models.py

Fixing notes from Sprint 13 PR

sprint 13 fixes

---

talentmap_api/position/filters.py
talentmap_api/user_profile/filters.py

Tweak FTS filters

---

talentmap_api/integrations/synchronization_helpers.py

Fix SOAP accounts

---

talentmap_api/common/management/commands/create_demo_environment.py

- Create demo environment will pad the positions to 6000, and clients for Leah to 600
- Performance remains good; however, full text search slows down just a tad (about 3 seconds) - we can look into ways to speed this up.

Create demo environment pad positions and clients

---

talentmap_api/common/management/commands/create_demo_environment.py

Use OS Random to fix Bandit errors.

Use OS Random

---

EXAMPLE_setup_environment.sh
talentmap_api/integrations/synchronization_helpers.py
talentmap_api/settings.py

Rc 1 adfs soap fixes

---

talentmap_api/user_profile/models.py
talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/tests/test_calculated_fields.py

- Add user's initials to their profile
- Add tests
@mjoyce91

User profile initials

---

talentmap_api/user_profile/models.py
talentmap_api/user_profile/serializers.py
talentmap_api/user_profile/tests/test_calculated_fields.py

- Add user's initials to their profile
- Add tests
@mjoyce91

(RC1) User profile initials

---

talentmap_api/common/common_helpers.py
talentmap_api/user_profile/tests/test_saved_searches.py

Fix an issue with saved searches when using `__in` filters
@mjoyce91

Saved search arrays

---

talentmap_api/common/common_helpers.py
talentmap_api/user_profile/tests/test_saved_searches.py

Fix an issue with saved searches when using `__in` filters
@mjoyce91

(RC1) Saved search arrays 

---

.codeclimate.yml
.coveragerc
locustfile.py
requirements.txt
talentmap_api/common/cache/key_constructor.py
talentmap_api/common/cache/views.py
talentmap_api/common/common_helpers.py
talentmap_api/common/tests/test_common_helpers.py
talentmap_api/conftest.py
talentmap_api/integrations/management/commands/synchronize_data.py
talentmap_api/integrations/models.py
talentmap_api/language/tests/test_language_endpoints.py
talentmap_api/language/views.py
talentmap_api/organization/views.py
talentmap_api/position/views/position.py
talentmap_api/settings.py
talentmap_api/urls.py

- Adds basic local memory caching
- Adds locust testing file
Will require packaging venv

(RC 1) Caching

---

talentmap_api/organization/tests/mommy_recipes.py
talentmap_api/position/models.py
talentmap_api/position/tests/test_position_endpoints.py
talentmap_api/position/urls/position.py
talentmap_api/position/views/position.py

- Add `/api/v1/position/{id}/similar` to retrieve a list of positions which are similar to the specified id
- Add tests for this endpoint
@mjoyce91

(RC1) Similar Positions

---

talentmap_api/settings.py

Modify ADFS mapping

---

talentmap_api/bidding/tests/test_bidcycle.py
talentmap_api/position/filters.py
talentmap_api/position/models.py
talentmap_api/position/serializers.py

- Add `/api/v1/position/?is_available_in_bidcycle={id},{id},{id}`
- Add `latest_bidcycle` to position serializer
- Add `is_highlighted` to position serializer

(RC1) Serializer Updates

---

talentmap_api/bidding/tests/test_bidcycle.py
talentmap_api/position/filters.py
talentmap_api/position/models.py
talentmap_api/position/serializers.py

- Add `/api/v1/position/?is_available_in_bidcycle={id},{id},{id}`
- Add `latest_bidcycle` to position serializer
- Add `is_highlighted` to position serializer

Serializer Updates

---

talentmap_api/organization/models.py

@mjoyce91 either reload your data in the database or call `python manage.py update_string_representations`

Switch City/Country ordering on locations

---

talentmap_api/common/filters.py

Allow 'in' on integer filters

---

talentmap_api/integrations/synchronization_helpers.py
talentmap_api/permission/views/group.py

@amirbey here are the requested changes for the sprint-17 PR.

Sprint 17 PR fixes

---

talentmap_api/common/filters.py
talentmap_api/organization/filters.py
talentmap_api/position/filters.py

(RC1) M2m in filters

---

.coveragerc
talentmap_api/common/filters.py
talentmap_api/common/tests/test_common_helpers.py
talentmap_api/common/tests/test_endpoints.py
talentmap_api/glossary/tests/test_glossary_crud.py
talentmap_api/user_profile/tests/test_user_profile_endpoints.py

- Add specific endpoint test for organization groups
- Exclude renderers from coverage
- Add/tweak tests for a few files to bump up coverage

Bumping up coverage, add organization group specific tests

---

talentmap_api/organization/models.py

Add new organization groups

---

talentmap_api/common/xml_helpers.py
talentmap_api/integrations/synchronization_helpers.py
talentmap_api/position/models.py
talentmap_api/settings.py

(RC1) Bug fixes s19

---

talentmap_api/common/xml_helpers.py
talentmap_api/integrations/synchronization_helpers.py
talentmap_api/position/models.py
talentmap_api/settings.py

Bug fixes s19

---

talentmap_api/position/models.py
talentmap_api/position/views/position.py

- Use distinct to prevent m2m duplicate items coming back for positions

Distinct positions

---

EXAMPLE_setup_environment.sh
talentmap_api/integrations/models.py

- Set a default timeout
- Catch timeout error
- Retry, and have max retries

SOAP timeout and retry

---

talentmap_api/bidding/models.py
talentmap_api/common/management/commands/update_relationships.py
talentmap_api/integrations/management/commands/import_data.py
talentmap_api/integrations/synchronization_helpers.py
talentmap_api/integrations/tests/test_soap_synchronization.py

* fix: set the collisiion field on cycle position
* fix: new job for the cycle position
* chore: fix test

fix: set the collision field on cycle position (#97)

---

talentmap_api/fsbid/filters.py
talentmap_api/fsbid/services.py
talentmap_api/fsbid/tests/test_fsbid_bid_seasons.py
talentmap_api/fsbid/tests/test_fsbid_bidlist.py
talentmap_api/fsbid/tests/test_fsbid_projected_vacancies.py
talentmap_api/fsbid/views/bid_seasons.py
talentmap_api/fsbid/views/bidlist.py
talentmap_api/fsbid/views/projected_vacancies.py
talentmap_api/settings.py

* feature: handle errors that fsbid may raise when submitting a bid
* adds endpoint to view list of logs available and get the contents of a particular log
* remove unnecessary imports
* log entry model managed should be false
* fixing linting issues
* additional lint errors fixed
* adding endpoints for running data sync ad hoc
* forcing superuser permission and removing unused imports and functions
* fix: remove posted date from PV. TM-909 (#94)
* feature: add endpoints for getting and updating the about page content. TM-912 (#93)
* feature: add endpoints for getting and updating the about page content. TM-912
* chore: update comment
* Fix/realign pv values. TM-909 (#96)
* fix: remove posted date from PV. TM-909
* fix: projected vacancy data matching new FSBid endpoints. TM-909
* fix: a …

dev -> staging (#132)

---

EXAMPLE_setup_environment.sh
talentmap_api/fsbid/filters.py
talentmap_api/fsbid/services.py
talentmap_api/fsbid/views/bid_seasons.py
talentmap_api/fsbid/views/bidlist.py
talentmap_api/fsbid/views/projected_vacancies.py
talentmap_api/organization/serializers.py
talentmap_api/settings.py

* feature: handle errors that fsbid may raise when submitting a bid
* adds endpoint to view list of logs available and get the contents of a particular log
* remove unnecessary imports
* log entry model managed should be false
* fixing linting issues
* additional lint errors fixed
* adding endpoints for running data sync ad hoc
* forcing superuser permission and removing unused imports and functions
* fix: remove posted date from PV. TM-909 (#94)
* feature: add endpoints for getting and updating the about page content. TM-912 (#93)
* feature: add endpoints for getting and updating the about page content. TM-912
* chore: update comment
* Fix/realign pv values. TM-909 (#96)
* fix: remove posted date from PV. TM-909
* fix: projected vacancy data matching new FSBid endpoints. TM-909
* fix: a …

Dev Testing (#137)
